service: indra-api

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: arn:aws:dynamodb:us-east-1:565700762908:table/indraTable

functions:
  search:
    handler: functions/search/handler.search
    package:
      patterns:
        - 'functions/search/handler.js'
    events:
      - http:
          path: search
          method: GET
          request:
            parameters:
              queryString:
                search: true
          cors: true
  save:
    handler: functions/save/handler.save
    events:
      - http:
          path: person
          method: POST
          request:
            schemas:
              application/json: ${file(schemas/personSchema.json)}
          cors: true
  getPerson:
    handler: functions/get/handler.get
    events:
      - http:
          path: person/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true
          cors: true
resources:
  Resources:
    indraTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: indraTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
